# Generated by Django 4.1 on 2022-09-02 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BranchID', models.CharField(max_length=250, verbose_name='Branch ID')),
                ('BranchName', models.CharField(max_length=250, verbose_name='Branch Name')),
                ('Description', models.TextField(blank=True, editable=False, null=True, verbose_name='Description')),
                ('CreatedAt', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('Status', models.BooleanField(default=True, editable=False, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branchs',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HospitalID', models.CharField(max_length=250, verbose_name='Hospital ID')),
                ('HospitalName', models.CharField(max_length=250, verbose_name='Hospital Name')),
                ('Description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('CreatedAt', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('Status', models.BooleanField(default=True, editable=False, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartmentID', models.CharField(max_length=250, verbose_name='Department ID')),
                ('DepartmentName', models.CharField(max_length=250, verbose_name='Department Name')),
                ('Description', models.TextField(blank=True, editable=False, null=True, verbose_name='Desccription')),
                ('Status', models.BooleanField(default=True, editable=False, verbose_name='Status of Visit Type')),
                ('CreatedAt', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('BranchID', models.ManyToManyField(to='facility.branch', verbose_name='Branch')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='HospitalID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facility.hospital', verbose_name='Hospital'),
        ),
    ]
