# Generated by Django 4.1 on 2022-09-02 23:25

from django.db import migrations, models
import facility.models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='BranchID',
            field=models.CharField(default=facility.models.generateBranchID, max_length=250, verbose_name='Branch ID'),
        ),
        migrations.AlterField(
            model_name='department',
            name='DepartmentID',
            field=models.CharField(default=facility.models.generateDepartmentID, max_length=250, verbose_name='Department ID'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='HospitalID',
            field=models.CharField(default=facility.models.generateHospitalID, max_length=250, verbose_name='Hospital ID'),
        ),
    ]
