# Generated by Django 4.1 on 2022-09-02 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillGroupCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BillGroupCategoryID', models.CharField(max_length=250, verbose_name='BillGroup Cat. ID')),
                ('BillGroupCategoryName', models.CharField(max_length=250, verbose_name='BillGroup Cat. Name')),
                ('Description', models.TextField(blank=True, editable=False, null=True, verbose_name='Description')),
                ('CreatedAt', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('Status', models.BooleanField(default=True, editable=False, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'BillGroupCategory',
                'verbose_name_plural': 'BillGroupCategorys',
            },
        ),
        migrations.CreateModel(
            name='BillGroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BillGroupTypeID', models.CharField(max_length=250, verbose_name='BillGroup Type')),
                ('BillGroupTypeName', models.CharField(max_length=250, verbose_name='BillGroup Type Name')),
                ('Description', models.TextField(blank=True, editable=False, null=True, verbose_name='Description')),
                ('CreatedAt', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('Status', models.BooleanField(default=True, editable=False, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'BillGroup Type',
                'verbose_name_plural': 'BillGroup Types',
            },
        ),
        migrations.CreateModel(
            name='BillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BillGroupID', models.CharField(max_length=250, verbose_name='BillGroup ID')),
                ('BillGroupName', models.CharField(max_length=250, verbose_name='BillGroup Name')),
                ('Description', models.TextField(blank=True, editable=False, null=True, verbose_name='Description')),
                ('CreatedAt', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('Status', models.BooleanField(default=True, editable=False, verbose_name='Status')),
                ('BillGroupCategoryID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.billgroupcategory', verbose_name='BillGroup Cat.')),
                ('BillGroupTypeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.billgrouptype', verbose_name='BillGroup Type')),
            ],
            options={
                'verbose_name': 'BillGroup',
                'verbose_name_plural': 'BillGroups',
            },
        ),
    ]
