# Generated by Django 4.1 on 2022-09-02 23:04

import billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billgroupcategory',
            options={'verbose_name': 'BillGroup Category', 'verbose_name_plural': 'BillGroup Categories'},
        ),
        migrations.AlterField(
            model_name='billgroupcategory',
            name='BillGroupCategoryID',
            field=models.CharField(default=billing.models.generateBillGroupCategoryID, max_length=250, verbose_name='BillGroup Cat. ID'),
        ),
    ]
