# Generated by Django 4.1 on 2022-08-20 18:37

from django.db import migrations, models
import django.db.models.deletion
import sponsor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0013_alter_patient_maritalstatusid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BillingCategoryID', models.CharField(max_length=250, verbose_name='Insurance Type ID')),
                ('BillingCategoryName', models.CharField(max_length=250, verbose_name='Insurance Type Name')),
                ('ConsultationPercent', models.IntegerField(blank=True, default=100, null=True, verbose_name='Consultation Percentage')),
                ('DrugPercent', models.IntegerField(blank=True, default=100, null=True, verbose_name='Drug Percentage')),
                ('ServicePercent', models.IntegerField(blank=True, default=100, null=True, verbose_name='Service Percentage')),
                ('ItemPercent', models.IntegerField(blank=True, default=100, null=True, verbose_name='Item Percentage')),
                ('TreatmentPercent', models.IntegerField(blank=True, default=100, null=True, verbose_name='Treatment Percentage')),
                ('DiagnosisPercent', models.IntegerField(blank=True, default=100, null=True, verbose_name='Diagnosis Percentage')),
                ('LabTestercent', models.IntegerField(blank=True, default=100, null=True, verbose_name='Lab Test Percentage')),
                ('BedPercent', models.IntegerField(blank=True, default=100, null=True, verbose_name='Bed Percentage')),
            ],
            options={
                'verbose_name': 'Billing Category',
                'verbose_name_plural': 'Billing Categories',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartmentID', models.CharField(default=sponsor.models.departmentID, max_length=250, verbose_name='Department ID')),
                ('DepartmentName', models.CharField(max_length=250, verbose_name='Department Name')),
                ('Description', models.TextField(blank=True, editable=False, null=True, verbose_name='Description')),
                ('Status', models.BooleanField(default=True, editable=False, verbose_name='Sponsor Type Status')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='InsuranceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InsuranceGroupID', models.CharField(max_length=250, verbose_name='Insurance Group ID')),
                ('InsuranceGroupName', models.CharField(max_length=520, verbose_name='Insurance Group Name')),
                ('Description', models.TextField(blank=True, editable=False, null=True, verbose_name='Description')),
                ('Status', models.BooleanField(default=True, editable=False, verbose_name='Billing Account Status')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Insurance Group',
                'verbose_name_plural': 'Insurance Groups',
            },
        ),
        migrations.CreateModel(
            name='MainAccountHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainAccountHolderID', models.CharField(default=sponsor.models.mainAccountHolderID, max_length=250, verbose_name='Dependant ID')),
                ('MainAccountHolderName', models.CharField(max_length=50, verbose_name='Dependant Name')),
                ('Description', models.TextField(blank=True, editable=False, null=True, verbose_name='Description')),
                ('Status', models.BooleanField(default=True, editable=False, verbose_name='Sponsor Type Status')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Main Account Holder',
                'verbose_name_plural': 'Main Account Holders',
            },
        ),
        migrations.CreateModel(
            name='ReceiptType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReceiptTypeID', models.CharField(max_length=250, verbose_name='ReceiptTypeID')),
                ('ReceiptTypeName', models.CharField(max_length=50, verbose_name='Receipt Type Name')),
                ('Description', models.TextField(blank=True, editable=False, null=True, verbose_name='Description')),
                ('Status', models.BooleanField(default=True, editable=False, verbose_name='Billing Account Status')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Receipt Type',
                'verbose_name_plural': 'Receipt Types',
            },
        ),
        migrations.CreateModel(
            name='SponsorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SponsorStatusID', models.CharField(default=sponsor.models.sponsorStatusID, max_length=250, verbose_name='Sponsor Status ID')),
                ('SponsorStatusName', models.CharField(max_length=250, verbose_name='Sponsor Status Name')),
                ('Description', models.TextField(blank=True, editable=False, null=True, verbose_name='Description')),
                ('Status', models.BooleanField(default=True, editable=False, verbose_name='Status')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Sponsor Status',
                'verbose_name_plural': 'Sponsor Statuses',
            },
        ),
        migrations.CreateModel(
            name='SponsorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SponsorTypeID', models.CharField(default=sponsor.models.sponsorTypeID, max_length=255, verbose_name='Sponsor Type ID')),
                ('SponsorTypeName', models.CharField(max_length=255, verbose_name='Sponsor Type Name')),
                ('Description', models.TextField(blank=True, editable=False, null=True, verbose_name='Description')),
                ('Status', models.BooleanField(default=True, editable=False, verbose_name='Sponsor Type Status')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Sponsor Type',
                'verbose_name_plural': 'Sponsor Types',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SponsorID', models.CharField(default=sponsor.models.sponsorID, max_length=250, verbose_name='Sponsor ID')),
                ('SponsorName', models.CharField(max_length=250, verbose_name='Sponsor Name')),
                ('Address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('City', models.CharField(max_length=250, verbose_name='City')),
                ('Location', models.CharField(blank=True, max_length=250, null=True, verbose_name='Location')),
                ('OfficePhone', models.CharField(max_length=250, verbose_name='Office Phone')),
                ('OfficeFax', models.CharField(max_length=250, verbose_name='Office Fax')),
                ('Description', models.TextField(blank=True, editable=False, null=True, verbose_name='Description')),
                ('Status', models.BooleanField(default=True, editable=False, verbose_name='Sponsor Type Status')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('SponsorStatusID', models.ForeignKey(max_length=250, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsor.sponsorstatus', verbose_name='Sponsor Status')),
                ('SponsorTypeID', models.ForeignKey(max_length=250, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsor.sponsortype', verbose_name='Sponsor Type')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
            },
        ),
        migrations.CreateModel(
            name='InsuranceScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InsuranceSchemeID', models.CharField(max_length=250, verbose_name='Insurance Scheme ID')),
                ('InsuranceSchemeName', models.CharField(max_length=250, verbose_name='Insurance Scheme Name')),
                ('Description', models.TextField(blank=True, editable=False, null=True, verbose_name='Description')),
                ('Status', models.BooleanField(default=True, editable=False, verbose_name='Billing Account Status')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('BillingCategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsor.billingcategory', verbose_name='Billing Category')),
                ('ReceiptTypeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsor.receipttype', verbose_name='Receipt Type')),
                ('SponsorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsor.sponsor', verbose_name='Sponsor')),
            ],
            options={
                'verbose_name': 'Insurance Scheme',
                'verbose_name_plural': 'Insurance Schemes',
            },
        ),
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BillingAccountID', models.CharField(default=sponsor.models.billingAccountID, max_length=250, verbose_name='Billing Account ID')),
                ('BillingAccountName', models.CharField(blank=True, editable=False, max_length=250, verbose_name='Billing Account')),
                ('InsuranceNumber', models.CharField(max_length=250, verbose_name='Insurance Number')),
                ('Description', models.TextField(blank=True, editable=False, null=True, verbose_name='Description')),
                ('Status', models.BooleanField(default=True, editable=False, verbose_name='Billing Account Status')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('DepartmentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsor.department', verbose_name='Department')),
                ('InsuranceSchemeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsor.insurancescheme', verbose_name='Sponsor Account')),
                ('MainAccountHolderID', models.ForeignKey(default=13, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsor.mainaccountholder', verbose_name='Main Bill Account')),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.patient', verbose_name='Patient')),
                ('RelationTypeID', models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='records.relationtype', verbose_name='Relation')),
            ],
            options={
                'verbose_name': 'Billing Account',
                'verbose_name_plural': 'Billing Accounts',
            },
        ),
    ]
