# Generated by Django 4.1 on 2022-08-20 14:36

from django.db import migrations, models
import django.db.models.deletion
import sponsor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0013_alter_patient_maritalstatusid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartmentID', models.CharField(max_length=250, verbose_name='Department ID')),
                ('DepartmentName', models.CharField(max_length=250, verbose_name='Department Name')),
                ('Description', models.TextField(blank=True, editable=False, null=True, verbose_name='Description')),
                ('Status', models.BooleanField(default=True, editable=False, verbose_name='Sponsor Type Status')),
                ('CreatedAt', models.DateField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='MainAccountHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainAccountHolderID', models.CharField(max_length=250, verbose_name='Dependant ID')),
                ('MainAccountHolderName', models.CharField(max_length=50, verbose_name='Dependant Name')),
                ('Description', models.TextField(blank=True, editable=False, null=True, verbose_name='Description')),
                ('Status', models.BooleanField(default=True, editable=False, verbose_name='Sponsor Type Status')),
                ('CreatedAt', models.DateField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Dependant',
                'verbose_name_plural': 'Dependants',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SponsorID', models.CharField(default=sponsor.models.sponsorID, max_length=250, verbose_name='Sponsor')),
                ('SponsorName', models.CharField(max_length=250, verbose_name='Sponsor Name')),
                ('SponsorTypeID', models.CharField(max_length=250, verbose_name='Sponsor Type')),
                ('SponsorStatusID', models.CharField(max_length=250, verbose_name='Sponsor Status')),
                ('Address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('City', models.CharField(max_length=250, verbose_name='City')),
                ('Location', models.CharField(blank=True, max_length=250, null=True, verbose_name='Location')),
                ('OfficePhone', models.CharField(max_length=250, verbose_name='Office Phone')),
                ('OfficeFax', models.CharField(max_length=250, verbose_name='Office Fax')),
                ('Description', models.TextField(blank=True, editable=False, null=True, verbose_name='Description')),
                ('Status', models.BooleanField(default=True, editable=False, verbose_name='Sponsor Type Status')),
                ('CreatedAt', models.DateField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
            },
        ),
        migrations.CreateModel(
            name='SponsorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SponsorStatusID', models.CharField(default=sponsor.models.sponsorStatusID, max_length=250, verbose_name='Sponsor Status ID')),
                ('SponsorStatusName', models.CharField(max_length=250, verbose_name='Sponsor Status Name')),
                ('Description', models.TextField(blank=True, editable=False, null=True, verbose_name='Description')),
                ('Status', models.BooleanField(default=True, editable=False, verbose_name='Status')),
                ('CreatedAt', models.DateField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Sponsor Status',
                'verbose_name_plural': 'Sponsor Statuses',
            },
        ),
        migrations.CreateModel(
            name='SponsorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SponsorTypeID', models.CharField(max_length=255, verbose_name='Sponsor Type ID')),
                ('SponsorTypeName', models.CharField(max_length=255, verbose_name='Sponsor Type Name')),
                ('Description', models.TextField(blank=True, editable=False, null=True, verbose_name='Description')),
                ('Status', models.BooleanField(default=True, editable=False, verbose_name='Sponsor Type Status')),
            ],
            options={
                'verbose_name': 'Sponsor Type',
                'verbose_name_plural': 'Sponsor Types',
            },
        ),
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BillingAccountID', models.CharField(max_length=250, verbose_name='Billing Account ID')),
                ('BillingAccountName', models.CharField(blank=True, editable=False, max_length=250, verbose_name='Billing Account')),
                ('InsuranceNumber', models.CharField(max_length=250, verbose_name='Insurance Number')),
                ('Description', models.TextField(blank=True, editable=False, null=True, verbose_name='Description')),
                ('Status', models.BooleanField(default=True, editable=False, verbose_name='Billing Account Status')),
                ('CreatedAt', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('MainAccountHolderID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsor.mainaccountholder', verbose_name='Main Bill Account')),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.patient', verbose_name='Patient')),
                ('RelationTypeID', models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='records.relationtype', verbose_name='Relation')),
                ('SponsorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsor.sponsor', verbose_name='Sponsor Account')),
            ],
            options={
                'verbose_name': 'Billing Account',
                'verbose_name_plural': 'Billing Accounts',
            },
        ),
    ]
