# Generated by Django 4.1 on 2022-08-20 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaccount',
            name='MainAccountHolderID',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsor.mainaccountholder', verbose_name='Main Bill Account'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='SponsorStatusID',
            field=models.ForeignKey(default=1, max_length=250, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsor.sponsorstatus', verbose_name='Sponsor Status'),
        ),
    ]
