# Generated by Django 4.1 on 2022-08-20 14:52

from django.db import migrations, models
import django.utils.timezone
import sponsor.models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsortype',
            name='CreatedAt',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billingaccount',
            name='BillingAccountID',
            field=models.CharField(default=sponsor.models.billingAccountID, max_length=250, verbose_name='Billing Account ID'),
        ),
        migrations.AlterField(
            model_name='department',
            name='DepartmentID',
            field=models.CharField(default=sponsor.models.departmentID, max_length=250, verbose_name='Department ID'),
        ),
        migrations.AlterField(
            model_name='mainaccountholder',
            name='MainAccountHolderID',
            field=models.CharField(default=sponsor.models.mainAccountHolderID, max_length=250, verbose_name='Dependant ID'),
        ),
        migrations.AlterField(
            model_name='sponsortype',
            name='SponsorTypeID',
            field=models.CharField(default=sponsor.models.sponsorTypeID, max_length=255, verbose_name='Sponsor Type ID'),
        ),
    ]
