# Generated by Django 4.1 on 2022-08-20 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0003_alter_billingaccount_relationtypeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaccount',
            name='ExpiryDate',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='SponsorStatusID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsor.sponsorstatus', verbose_name='Status'),
        ),
    ]
