# Generated by Django 4.1 on 2022-08-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0006_billingaccount_receipttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaccount',
            name='CreatedAt',
            field=models.DateField(auto_now_add=True, verbose_name='Created At'),
        ),
    ]
