# Generated by Django 4.1 on 2022-08-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0007_alter_billingaccount_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaccount',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
    ]
