# Generated by Django 4.1 on 2022-09-03 01:21

import cashier.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='InvoiceID',
            field=models.CharField(default=cashier.models.generateInvoiceID, max_length=250, verbose_name='Invoice No.'),
        ),
        migrations.AlterField(
            model_name='paymentmode',
            name='PaymentModeID',
            field=models.CharField(default=cashier.models.generatePaymentModeID, max_length=250, verbose_name='Payment Mode ID'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='PaymentTypeID',
            field=models.CharField(default=cashier.models.generatePaymentTypeID, max_length=250, verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='ReceiptID',
            field=models.CharField(default=cashier.models.generateReceiptID, max_length=250, verbose_name='Receipt No.'),
        ),
    ]
