# Generated by Django 4.1 on 2022-08-17 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='CountryID',
            field=models.ForeignKey(blank=True, default='NONE', null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='MaritalStatusID',
            field=models.ForeignKey(blank=True, default='NONE', on_delete=django.db.models.deletion.SET_DEFAULT, to='records.maritalstatus', verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='OtherName',
            field=models.CharField(blank=True, max_length=255, verbose_name='Other Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='PatientDependentTypeID',
            field=models.ForeignKey(blank=True, default='SELF', on_delete=django.db.models.deletion.SET_DEFAULT, to='records.dependenttype', verbose_name='Dependent'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='PatientInsNo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Patient Insurance Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='PatientInsSchemeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.patientinsscheme', verbose_name='Patient Insurance Scheme'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ReligionID',
            field=models.ForeignKey(blank=True, default='NONE', null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.religion', verbose_name='Religion'),
        ),
    ]
