# Generated by Django 4.1 on 2022-08-17 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_patient_countryid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='MaritalStatusID',
            field=models.ForeignKey(blank=True, default='NONE', null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.maritalstatus', verbose_name='Marital Status'),
        ),
    ]
