# Generated by Django 4.1 on 2022-08-17 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_patient_maritalstatusid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='PatientDependentTypeID',
            field=models.ForeignKey(blank=True, default='SELF', null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.dependenttype', verbose_name='Dependent'),
        ),
    ]
