# Generated by Django 4.1 on 2022-08-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_remove_patient_patientinsno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextofkin',
            name='Status',
            field=models.BooleanField(default=True, editable=False, verbose_name='Next of Kin Status'),
        ),
    ]
