# Generated by Django 4.1 on 2022-08-17 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_alter_nextofkin_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nextofkin',
            name='EntryDate',
        ),
        migrations.RemoveField(
            model_name='nextofkin',
            name='IdentificationNumber',
        ),
        migrations.RemoveField(
            model_name='nextofkin',
            name='IdentificationTypeID',
        ),
        migrations.RemoveField(
            model_name='nextofkin',
            name='KeyPrefix',
        ),
        migrations.RemoveField(
            model_name='nextofkin',
            name='PatientRankID',
        ),
        migrations.RemoveField(
            model_name='nextofkin',
            name='PatientRankLevelID',
        ),
        migrations.RemoveField(
            model_name='nextofkin',
            name='PatientUnitID',
        ),
        migrations.RemoveField(
            model_name='nextofkin',
            name='Profession',
        ),
        migrations.RemoveField(
            model_name='nextofkin',
            name='ServiceNo',
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='RelationTypeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.relationtype', verbose_name='Relation To Patient'),
        ),
    ]
