# Generated by Django 4.1 on 2022-08-17 20:38

from django.db import migrations, models
import records.models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_remove_nextofkin_patienttypeid_patientidentification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='Status',
            field=models.BooleanField(default=True, editable=False, verbose_name='Country Status'),
        ),
        migrations.AlterField(
            model_name='dependenttype',
            name='Status',
            field=models.BooleanField(default=True, editable=False, verbose_name='Dependent Type Status'),
        ),
        migrations.AlterField(
            model_name='identificationtype',
            name='Status',
            field=models.BooleanField(default=True, verbose_name='Identification Type Status'),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='DateOfBirth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='NextOfKinID',
            field=models.CharField(default=records.models.generateNextOfKinID, max_length=255, unique=True, verbose_name='Next of Kin ID'),
        ),
        migrations.AlterField(
            model_name='patientinsscheme',
            name='Status',
            field=models.BooleanField(default=True, editable=False, verbose_name='Relation Type Status'),
        ),
        migrations.AlterField(
            model_name='patientrank',
            name='Status',
            field=models.BooleanField(default=True, editable=False, verbose_name='Patient Rank Status'),
        ),
        migrations.AlterField(
            model_name='patientranklevel',
            name='Status',
            field=models.BooleanField(default=True, verbose_name='Patient Rank Level Status'),
        ),
        migrations.AlterField(
            model_name='patientunit',
            name='Status',
            field=models.BooleanField(default=True, verbose_name='Patient Unit Status'),
        ),
        migrations.AlterField(
            model_name='religion',
            name='Status',
            field=models.BooleanField(default=True, editable=False, verbose_name='Religion Status'),
        ),
    ]
