# Generated by Django 4.1 on 2022-08-17 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_alter_country_status_alter_dependenttype_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientCategoryName', models.CharField(max_length=255, verbose_name='Patient Category Name')),
                ('Description', models.TextField(blank=True, null=True)),
                ('Status', models.BooleanField(default=True, editable=False, verbose_name='Patient Rank Status')),
            ],
            options={
                'verbose_name': 'Patient Category',
                'verbose_name_plural': 'Patient Categories',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='PatientRank',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.patientrank', verbose_name='Patient Level'),
        ),
        migrations.AddField(
            model_name='patient',
            name='PatientRankLevel',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.patientranklevel', verbose_name='Patient Rank Level'),
        ),
        migrations.AlterField(
            model_name='dependenttype',
            name='DependentName',
            field=models.CharField(max_length=255, verbose_name='Dependent Type'),
        ),
        migrations.AddField(
            model_name='patient',
            name='PatientCategory',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.patientcategory', verbose_name='Patient Category'),
        ),
    ]
