# Generated by Django 4.1 on 2022-08-17 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_patientcategory_patient_patientrank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='PatientCategory',
            field=models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.patientcategory', verbose_name='Patient Category'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='PatientRank',
            field=models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.patientrank', verbose_name='Patient Level'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='PatientRankLevel',
            field=models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.patientranklevel', verbose_name='Patient Rank Level'),
        ),
    ]
