# Generated by Django 4.1 on 2022-08-18 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_alter_patient_patientcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='MaritalStatusID',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.maritalstatus', verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='PatientCategory',
            field=models.ForeignKey(blank=True, default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.patientcategory', verbose_name='Patient Category'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='PatientRank',
            field=models.ForeignKey(blank=True, default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.patientrank', verbose_name='Patient Level'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='PatientRankLevel',
            field=models.ForeignKey(blank=True, default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.patientranklevel', verbose_name='Patient Rank Level'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='PatientTypeID',
            field=models.ForeignKey(default='1', editable=False, on_delete=django.db.models.deletion.SET_DEFAULT, to='records.patienttype', verbose_name='Patient Type'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ResidencePhone',
            field=models.CharField(max_length=255, verbose_name='Residence Phone'),
        ),
    ]
