# Generated by Django 4.1 on 2022-08-20 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_alter_patient_maritalstatusid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='GenderID',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.gender', verbose_name='Gender'),
        ),
    ]
