# Generated by Django 4.1 on 2022-08-20 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_alter_patient_genderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='CountryID',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ReligionID',
            field=models.ForeignKey(blank=True, default='3', null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.religion', verbose_name='Religion'),
        ),
    ]
