# Generated by Django 4.1 on 2022-08-20 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_alter_patient_countryid_alter_patient_religionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextofkin',
            name='RelationTypeID',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.relationtype', verbose_name='Relation To Patient'),
        ),
        migrations.AlterField(
            model_name='patientidentification',
            name='IdentificationType',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.identificationtype', verbose_name='Type of Identification'),
        ),
    ]
