# Generated by Django 4.1 on 2022-08-20 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_alter_nextofkin_relationtypeid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='PatientCategory',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.patientcategory', verbose_name='Patient Category'),
        ),
    ]
