# Generated by Django 4.1 on 2022-08-20 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_alter_patient_patientcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='PatientRank',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.patientrank', verbose_name='Patient Level'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='PatientRankLevel',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.patientranklevel', verbose_name='Patient Rank Level'),
        ),
    ]
