# Generated by Django 4.1 on 2022-09-02 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility', '0001_initial'),
        ('sponsor', '0008_alter_billingaccount_createdat'),
        ('cashier', '0001_initial'),
        ('consultation', '0001_initial'),
        ('records', '0018_alter_patient_patientrank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VisitStatusID', models.CharField(max_length=250, verbose_name='Visit Status ID')),
                ('VisitStatusName', models.CharField(editable=False, max_length=250, verbose_name='Visit Status Name')),
                ('ManualVisitNumber', models.CharField(max_length=250, verbose_name='Manual Visit Number')),
                ('Description', models.TextField(blank=True, editable=False, null=True, verbose_name='Desccription')),
                ('Status', models.BooleanField(default=True, editable=False, verbose_name='Status of Visit Type')),
                ('CreatedAt', models.DateField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Visit Status',
                'verbose_name_plural': 'Visit Statuses',
            },
        ),
        migrations.CreateModel(
            name='VisitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VisitTypeID', models.CharField(max_length=250, verbose_name='Visit Type ID')),
                ('VisitTypeName', models.CharField(max_length=50, verbose_name='Visit Type')),
                ('VisitTypeCost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Visit Type Cost')),
                ('Description', models.TextField(blank=True, editable=False, null=True, verbose_name='Desccription')),
                ('Status', models.BooleanField(default=True, editable=False, verbose_name='Status of Visit Type')),
                ('CreatedAt', models.DateField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Visit Type',
                'verbose_name_plural': 'Visit Types',
            },
        ),
        migrations.CreateModel(
            name='Visitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VisitationID', models.CharField(default=True, max_length=250, unique=True, verbose_name='Visitation ID')),
                ('VisitationName', models.CharField(blank=True, editable=False, max_length=250, verbose_name='Visitation Name')),
                ('VisitationFee', models.CharField(max_length=250, verbose_name='Consultation Fee')),
                ('ManualReceiptNumber', models.CharField(blank=True, max_length=250, null=True, verbose_name='Manual Receipt Number')),
                ('VisitDate', models.DateField(auto_now_add=True, verbose_name='Visit Date')),
                ('Description', models.TextField(blank=True, editable=False, null=True, verbose_name='Desccription')),
                ('Status', models.BooleanField(default=True, editable=False, verbose_name='Status of Visit Type')),
                ('CreatedAt', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('BillingAccountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsor.billingaccount', verbose_name='Billing Account')),
                ('ConsultationTypeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultation.consultationtype', verbose_name='Consultation Type')),
                ('DepartmentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facility.department', verbose_name='Department')),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.patient', verbose_name='Patient')),
                ('ReceiptNumber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashier.receipt', verbose_name='Receipt')),
                ('VisitStatusID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visitation.visitstatus', verbose_name='Status')),
                ('VisitTypeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visitation.visittype', verbose_name='Visit Type')),
            ],
            options={
                'verbose_name': 'Visitation',
                'verbose_name_plural': 'Visitations',
            },
        ),
    ]
