# Generated by Django 4.1 on 2022-09-03 00:04

from django.db import migrations, models
import visitation.models


class Migration(migrations.Migration):

    dependencies = [
        ('visitation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitstatus',
            name='VisitStatusID',
            field=models.CharField(default=visitation.models.generateVisitStatusID, max_length=250, verbose_name='Visit Status ID'),
        ),
        migrations.AlterField(
            model_name='visittype',
            name='VisitTypeCost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Visit Type Cost'),
        ),
        migrations.AlterField(
            model_name='visittype',
            name='VisitTypeID',
            field=models.CharField(default=visitation.models.generateVisitTypeID, max_length=250, verbose_name='Visit Type ID'),
        ),
    ]
