# Generated by Django 4.1 on 2022-09-03 00:18

from django.db import migrations, models
import visitation.models


class Migration(migrations.Migration):

    dependencies = [
        ('visitation', '0004_alter_visitstatus_visitstatusname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitation',
            name='VisitationID',
            field=models.CharField(default=visitation.models.generateVisitationID, max_length=250, unique=True, verbose_name='Visitation ID'),
        ),
    ]
