# Generated by Django 4.1 on 2022-09-02 23:49

import consultation.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_billgroup_billgroupid_and_more'),
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationtype',
            name='BillGroupID',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.billgroup', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='consultationtype',
            name='CashConsultationFee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cash Cons. Fee'),
        ),
        migrations.AlterField(
            model_name='consultationtype',
            name='ConsultationTypeID',
            field=models.CharField(default=consultation.models.generateConsultationTypeID, max_length=250, verbose_name='Consultation Type ID'),
        ),
    ]
